name: Feature Branch Build

permissions:
  contents: read

on:
  push:
    branches:
      - "feat/**"
    paths-ignore:
      - "README.md"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history needed for GitVersion

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: "5.x"

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Display Version
        run: |
          echo "SemVer: ${{ env.GitVersion_SemVer }}"
          echo "NuGet Version: ${{ env.GitVersion_NuGetVersion }}"

      - name: Restore dependencies
        run: dotnet restore src/LinkupSdk.csproj

      - name: Build for .NET 8.0
        run: dotnet build --no-restore --configuration Release --framework net8.0 src/LinkupSdk.csproj

      - name: Build for .NET 9.0
        run: dotnet build --no-restore --configuration Release --framework net9.0 src/LinkupSdk.csproj

      - name: Build for .NET 10.0
        run: dotnet build --no-restore --configuration Release --framework net10.0 src/LinkupSdk.csproj

      - name: Run Tests for .NET 8.0
        run: dotnet test --no-build --configuration Release --framework net8.0 --logger trx --results-directory ./TestResults

      - name: Run Tests for .NET 9.0
        run: dotnet test --no-build --configuration Release --framework net9.0 --logger trx --results-directory ./TestResults

      - name: Run Tests for .NET 10.0
        run: dotnet test --no-build --configuration Release --framework net10.0 --logger trx --results-directory ./TestResults

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./TestResults

      - name: Pack NuGet Package
        run: |
          # Create NuGet package for all target frameworks
          dotnet pack src/LinkupSdk.csproj --no-build --configuration Release --output ./nupkgs
